# Generated by Django 4.1.3 on 2024-09-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contestant",
            name="photo",
        ),
        migrations.AddField(
            model_name="contestant",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="contestant_images/"
            ),
        ),
    ]
