# Generated by Django 4.1.3 on 2024-09-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_remove_contestant_photo_contestant_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="voter_id",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
